version: version.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o version version.cu
vector: vector.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o vector vector.cu
algo-Transformations: algo-Transformations.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o algo-Transformations algo-Transformations.cu
algo-Reduction: algo-Reduction.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o algo-Reduction algo-Reduction.cu
algo-Scan: algo-Scan.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o algo-Scan algo-Scan.cu
algo-Reordering: algo-Reordering.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o algo-Reordering algo-Reordering.cu
algo-Sort: algo-Sort.cu
	nvcc -I /usr/local/cuda/samples/common/inc -o algo-Sort algo-Sort.cu
clean:
	rm version vector algo-Transformations algo-Reduction algo-Scan algo-Reduction algo-Reordering algo-Sort
